import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "cal-sans";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <main className='flex-1 min-h-screen bg-[#F0F7FF] pb-20'>
            {children}
          </main>
          <footer className='flex-init'>
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
