import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const satoshi = localFont({
  src: '../assets/fonts/Satoshi-Variable.woff2',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={satoshi.className}>
        <div className="">
          <main className="flex-1 min-h-screen bg-[#F0F7FF] pb-20">
            {children}
          </main>
          <footer className="flex-init">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
